name: "Release Action" # Nom de l'action

description: "Une action pour gérer les releases" # Description courte

inputs:
  tag_name: # Entrée pour le nom du tag
    description: "Nom du tag à créer" # Description
    required: true # Obligatoire

  release_notes: # Entrée pour les notes de release
    description: "Notes de la release" # Description
    required: false # Optionnel

  github_token: # Entrée pour le token GitHub
    description: "GitHub token pour l'authentification" # Description
    required: true # Obligatoire

runs:
  using: "composite" # Type composite
  steps:
    - name: Créer un tag Git # Étape pour créer un tag
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag ${{ inputs.tag_name }}
        git push origin ${{ inputs.tag_name }}
      shell: bash # Spécifie l'interpréteur de commandes

    - name: Créer une release GitHub # Étape pour créer une release
      if: ${{ inputs.release_notes }}
      run: |
        curl -X POST \
          -H "Authorization: token ${{ inputs.github_token }}" \
          -H "Content-Type: application/json" \
          -d '{"tag_name": "${{ inputs.tag_name }}", "name": "${{ inputs.tag_name }}", "body": "${{ inputs.release_notes }}"}' \
          https://api.github.com/repos/${{ github.repository }}/releases
      shell: bash # Spécifie l'interpréteur de commandes
