# Simple Dockerfile for a Spring Boot fat jar
# Build the jar with: mvnw package -DskipTests

FROM eclipse-temurin:21-jdk-alpine AS build
WORKDIR /app
COPY . /app
# Exécute la commande de build pour créer le jar dans le conteneur
RUN ./mvnw -B -DskipTests package

FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app
# Copie le jar généré depuis l'étape de build vers l'image finale
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]
